#ifndef ALGORITHMS_BASICDEFINE_DEFINE_H
#define ALGORITHMS_BASICDEFINE_DEFINE_H

#ifndef LINE_INFO
#define LINE_INFO "\n[" << __FILE__ << " : line " << __LINE__ << " : " << __FUNCTION__ << "()] - "
#endif

#ifndef TRACE_LINE
#define TRACE_LINE "\n[" << __FILE__ << " : line " << __LINE__ << " : " << __FUNCTION__ << "()]"
#endif

#ifndef UNUSED
#define UNUSED(x) (void*)x
#endif

/* Disallow copy and assign functions that generated by compiler. */
#define DISALLOW_COPY_AND_ASSIGN(TypeName) \
    TypeName(const TypeName &);            \
    TypeName &operator=(const TypeName &) 

#define OKAY  0
#define ERROR 1

#define NOT !
#define AND &&

#define EXIT exit(1)

#endif //ALGORITHMS_BASICDEFINE_DEFINE_H
